import './globals.css'
import type { Metadata } from 'next'
import Providers from "@/app/providers";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col mx-auto min-h-screen px-[1.5rem] sm:max-w-[73rem]">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
